require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10
