version: "3.9"

services:
  postgres:
    image: "postgres:14.5"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  redis:
    image: "redis:6.0.6"
    volumes:
      - "redis:/data"

  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    env_file: ./.env # !!! OVERRIDE IN OTHER places
    environment:
      - RAILS_ENV=development
    command: "bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    depends_on:
      - "postgres"
      - "redis"
    ports:
      - "3001:3000"

volumes:
  postgres:
  redis:
  gems:
